name: ci

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: sudo apt-get install -y tar shellcheck
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make PBG_VERSION=${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          files: "pixel-backup-gang-*.tar.gz"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
