name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make VERSION=$(git rev-parse --short HEAD)
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "pixel-backup-gang-$(git rev-parse --short HEAD).tar.gz"
